# [[main]]
#     identifier = "home"
#     name = "Home"
#     url = "/"
#     weight = 1

[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "ux-design"
    name = "UX Design"
    url = "/ux-design"
    weight = 2

# [[main]]
#     identifier = "architecture"
#     name = "Architecture"
#     url = "/architecture"
#     weight = 3

[[main]]
    identifier = "resume"
    name = "Resume ‚Üó"
    url = "/resume.pdf"
    weight = 4
    [main.params]
        target = "_blank"

[[main]]
    identifier = "linked-in"
    name = "LinkedIn ‚Üó"
    url = "https://www.linkedin.com/in/jefforshalick"
    weight = 5
    [main.params]
        target = "_blank"

[[main]]
    identifier = "email"
    name = "Email ‚Üó"
    url = "mailto:hi@jefforshalick.com"
    weight = 6
    



# [[main]]
#     identifier = "not-work"
#     name = "üíÉ Not Work"
#     url = "/not-work"
#     weight = 3

# [[main]]
#     identifier = "now"
#     name = "üï∞Ô∏è Now"
#     url = "/now"
#     weight = 4


# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/jefforshalick"
    weight = 1
    
[[social]]
    identifier = "Instagram"
    name = "Instagram"
    url = "https://www.instagram.com/jeffopalooza"
    weight = 2

[[social]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
    weight = 3

[[social]]
    identifier = "contact"
    name = "Contact"
    url = "mailto:hi@jefforshalick.com"
    weight = 4


# [[social]]
#     identifier = "Dribbble"
#     name = "Dribbble"
#     url = "https://dribbble.com/jefforshalick"
#     weight = 2