[[main]]
    identifier = "home"
    name = "ğŸ  Home"
    url = "/"
    weight = 1

[[main]]
    identifier = "work"
    name = "ğŸ‘¨â€ğŸ’» Work"
    url = "/work"
    weight = 2

[[main]]
    identifier = "not-work"
    name = "ğŸ’ƒ Not Work"
    url = "/not-work"
    weight = 3

# [[main]]
#     identifier = "about"
#     name = "ğŸ““ About"
#     url = "/"
#     weight = 1

# [[main]]
#     identifier = "now"
#     name = "ğŸ•°ï¸ Now"
#     url = "/now"
#     weight = 4

# [[main]]
#     identifier = "say-hi"
#     name = "ğŸ“¬ Say hey"
#     url = "/contact"
#     weight = 4

# [[main]]
#     identifier = "categories"
#     name = "Categories"
#     url = "/categories"
#     weight = 4

# [[main]]
#     identifier = "tags"
#     name = "Tags"
#     url = "/tags"
#     weight = 5

# [[main]]
#     identifier = "linkedin"
#     name = "LinkedIn"
#     url = "https://linkedin.com/in/jefforshalick"
#     weight = 5


# Social Media Configuration

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://linkedin.com/in/jefforshalick"
    weight = 1

[[social]]
    identifier = "resume"
    name = "Resume"
    url = "/resume.pdf"
    weight = 2